---
- name: install httpd server
  hosts: n1
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: install httpd
      service:
        name: httpd
        enabled: yes 
...

