---
    - name: update static
      copy:
        src: static.html
        dest: /var/www/html/static.html

    - name: update dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html    
...